### ISSUE TITLE
Trivial comments about the markup

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#11]
https://github.com/w3c/miniapp-packaging/blob/a5ab18f2f132fd697bcf063a71762b0b35929c67/index.html#L741

Because there is no `h7` in HTML, we should use another method to write this markup.

**Comment by espinr** [comment]
hahaha. True! I invented a new element :) Thanks @xfq. Changed to a nested list `ul`>`li` since it was list of profiles and values. Already done in #16
