### ISSUE TITLE
Length of file names

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#12]
https://w3c.github.io/miniapp-packaging/#file-names

> File Names MUST NOT exceed 255 bytes.

What if the file name is more than 255 bytes? Will the file name be truncated? The i18n WG has related guidelines here: https://w3c.github.io/bp-i18n-specdev/#char_truncation

**Comment by xfq** [comment]
Filed a similar issue against EPUB: https://github.com/w3c/epub-specs/issues/1629

**Comment by espinr** [comment]
I like @aphillips ' [comment](https://github.com/w3c/epub-specs/issues/1629#issuecomment-849720887) to minimize the impact. We could include a similar warning note in the spec:

> If a MiniApp vendor imposes length limits on path and file names, it is important to avoid mid-character truncation due to the difference between bytes and characters in multibyte encodings such as UTF-8. See the [text truncation best practice](https://w3c.github.io/bp-i18n-specdev/#char_truncation) for more information.

**Comment by r12a** [comment]
The link should point to the /TR version, ie. https://w3c.github.io/bp-i18n-specdev/#char_truncation

**Comment by r12a** [comment]
Sorry, that link should have been https://www.w3.org/TR/international-specs/#char_truncation

**Comment by espinr** [comment]
[Usage note included](https://w3c.github.io/miniapp-packaging/#file-names) with the text proposed in this thread. Thank you!
