### ISSUE TITLE
Refer to BCP 47

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#14]
https://w3c.github.io/miniapp-packaging/#sec-miniapp-i18n

The link to and name of BCP 47 was created specifically so that there is an unchanging reference to the definition of language tags. RFC4646 and RFC4647 are not the recommended method to refer to IETF language tags.

BCP 47 contains one RFC dedicated to the syntax and subtags of language tags, and another dedicated to specify items in a user's list of language preferences.

**Comment by zhangyongjing** [comment]
Shall we close it now?
