### ISSUE TITLE
Discussion of page configuration file

### ISSUE THREAD

**Issue by ShourenLan** [w3c/miniapp-packaging#3]
We may not need such a file (page.json) for mini app packages.

**Comment by espinr** [comment]
Since there is no restriction in the type of files we can add into a MiniApp package, I propose considering these `page.json` as optional resources. So we can focus only on:

- XML/HTML (templates)
- CSS (style)
- JS (logic)

Comments?

**Comment by espinr** [comment]
Closing. As discussed, JSON config page is optional as agreed. Already included in 736f1f6
