### ISSUE TITLE
Split content and packaging?

### ISSUE THREAD

**Issue by espinr** [w3c/miniapp-packaging#30]
The group is still discussing about the formats, document definition and manipulation (see issue #2)... In my opinion, the specification of the content (templating/binding/DOM manipulation) should be outside the Packaging spec (as its name indicates, it's just about the "envelope" and the processing of it). In any case, we should indicate the type of files and resources.

So, my question is if we should propose a new deliverable that complements the [UI Components spec](https://w3c.github.io/miniapp-components/) to describe the **content** of a MiniApp. So the packaging can be described in a generic way (structure and ZIP format), and the "MiniApp Content" specification may define how a MiniApp page is created in terms of:

- HTML content documents (HTML profile with the supported elements, extension of those we need to extend, or the XML application profile needed)
- CSS stylesheets (CSS profile since not all modules are supported, CSS extensions like -miniapp-orientation, -miniapp-page-width,...)
- Scripting documents (including the considerations in the Event Model)
- Templating (perhaps as a normative section)
- UI Components (link to the UI components document)
- APIs and Services (APIs supported)

This is something similar to the [approach followed by the EPUB group](https://www.w3.org/publishing/epub3/epub-contentdocs.html ). Since it is not part of the charter, I suppose we need to start it from the CG.

Opinions?

**Comment by zhangyongjing** [comment]
I think it's a reasonable proposal. Let's discuss this in the WG/CG call.

**Comment by Ternence** [comment]
Yes, I agree to create the  "MiniApp Content" specification that defined the special files' format and elements.

**Comment by xfq** [comment]
Discussions in yesterday's meeting: https://www.w3.org/2021/07/29-miniapp-minutes.html#t04

**Comment by espinr** [comment]
Moving this conversation to w3c/miniapp-components#7
