### ISSUE TITLE
Character restrictions on the file names

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#31]
https://w3c.github.io/miniapp-packaging/#file-names

> Non characters in Arabic Presentation Forms-A (U+FDDO … U+FDEF)

`U+FDDO` should be `U+FDD0` (zero instead of oh) here.

**Comment by espinr** [comment]
Thanks @xfq , well spotted. It's amended at the PR #33 ([see diff](https://pr-preview.s3.amazonaws.com/w3c/miniapp-packaging/33/1fc4004...espinr:ce55fa0.html#filename-normalization))

**Comment by xfq** [comment]
Thank you!
