### ISSUE TITLE
Case folding of the file names

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#32]
https://w3c.github.io/miniapp-packaging/#file-names

>   All File Names within the same directory MUST be unique following case normalization as described in section 3.13 of [Unicode].

This sentence does not seem to be very clear. Please refer to <a href="https://www.w3.org/TR/charmod-norm/#definitionCaseFolding">Case Mapping and Case Folding</a> and <a href="https://www.w3.org/TR/charmod-norm/#handlingCaseFolding">Additional Considerations for Case Folding</a> in [charmod-norm](https://www.w3.org/TR/charmod-norm/).

See https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames (and related PRs https://github.com/w3c/epub-specs/pull/1648 and https://github.com/w3c/epub-specs/pull/1692 ) for an example.

**Comment by espinr** [comment]
Thanks @xfq. It's amended at the PR #33 ([see diff](https://pr-preview.s3.amazonaws.com/w3c/miniapp-packaging/33/1fc4004...espinr:ce55fa0.html#filename-normalization))

**Comment by xfq** [comment]
Closing.
