### ISSUE TITLE
Security and privacy considerations

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#46]
I'm not a security expert, here are just a few security and privacy related considerations I can think of for the WG to discuss. We can split them into separate issues if needed.

### Add a separate Privacy Considerations section

Per [Privacy Reviews Guidelines](https://github.com/w3cping/privacy-request/blob/main/.github/ISSUE_TEMPLATE/request-review-for-a-wd-that-is-moving-to-cr-soon.md), we need to have a Privacy Considerations section, separate from Security Considerations.

Some things we may want to add about security and privacy include:

### Recommendations to MiniApp implementers

We can add some recommendations for MiniApp implementers, such as:

* User agents should examine all vectors of attack from a MiniApp package and protect against them, such as attack of one MiniApp against another in the same user agent, or pretending to be another MiniApp or website in order to steal user information.

* MiniApp user agents should also check the package for malicious scripts, links, remote resources, and so on.

* User agents should isolate MiniApps from each other. On the same device, user A must not be able to read user B's data in the local storage; and different MiniApps must not read and write data in the local storage to each other.

* Some MiniApp user agents may collect user data. We should recommend user agents to be clear about the data being collected and how it is used.

In addition, many MiniApp implementations (like [1](https://developers.weixin.qq.com/miniprogram/en/dev/framework/runtime/js-support.html) [2](https://opendocs.alipay.com/mini/framework/implementation-detail#%E5%AF%B9%E5%8A%A8%E6%80%81%E6%89%A7%E8%A1%8C%E8%84%9A%E6%9C%AC%E7%9A%84%E9%99%90%E5%88%B6) [3](https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/guide/mini-app-runtime/javascript-support/) [4](https://q.qq.com/wiki/develop/miniprogram/frame/useful/useful_env.html#%E8%BF%90%E8%A1%8C%E9%99%90%E5%88%B6)) disallow dynamic code loading like `eval` and `new Function` as a defense mechanism to stop XSS attacks. Currently, it is not mentioned in the [Scripting Resources](https://w3c.github.io/miniapp-packaging/#sec-miniapp-resources-js) section. Should we consider standardizing this?

### Recommendations to MiniApp developers

Should we write some security and privacy recommendations related to the *developer* of MiniApps, such as using HTTPS when requesting resources?

**Comment by espinr** [comment]
Good points @xfq , I've done the [self-review questionnaire](https://w3ctag.github.io/security-questionnaire/) and I've detected some similar points we need to address. I'm not a security expert either, so there may be more points I haven't seen.

**Comment by xfq** [comment]
Sounds good. If we decide we want to fix this by introducing a new member in the manifest, maybe we can open a new issue in the manifest repo.

Also, do we need to point out the difference between the security model of MiniApps and web apps?

**Comment by xfq** [comment]
Another thing: if there is a link to a web page in the MiniApp, will a new browser be instance opened? If so, its browsing context is isolated from the MiniApp, which should be more secure. We might want to mention this in the security section.

**Comment by xfq** [comment]
We now have a separate Privacy Considerations section and some recommendations. I think this issue can be closed. Separate issues about the security and privacy considerations sections can be opened for discussion if needed.
