### ISSUE TITLE
Required and optional files/directories

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#5]
https://w3c.github.io/miniapp/specs/packaging/

It would be useful to specify which files/directories are mandatory and which are optional.

**Comment by espinr** [comment]
To activate the discussion... 

So far this is the structure of the file system root directory:

>                 /
>                 |___manifest.json
>                 |___app.js
>                 |___app.css
>                 |___pages/
>                 |___common/
>                 |___i18n/

- `common` may be empty in some cases. Developers might want to organize their common resources using other naming schemas, or just organizing them by pages. 
- the main stylesheet, `app.css`, may be also empty.  If it is optional, should we keep the name reserved as `app.css`? so the MiniApp processor will be direct to the entry point by default?

**Comment by zhangyongjing** [comment]
I agree to reserving 'app.css' as default.

**Comment by zhangyongjing** [comment]
Shall we close it now?

**Comment by xfq** [comment]
Yes. Thank you!
