### ISSUE TITLE
Security and Privacy self-review

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-packaging#54]
We need to answer the [W3C Security and Privacy Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/).

**Comment by xfq** [comment]
Examples:

* [Web of Things (WoT)](https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md)
* [Secure Payment Confirmation](https://github.com/w3c/secure-payment-confirmation/blob/main/security-privacy-questionnaire.md)

**Comment by espinr** [comment]
Thanks @xfq , I already have a first version I used for defining the Privacy and Security sections in the spec.

I've created a PR (#55) with a the questionnaire. Everyone, feel free to comment and suggest changes!

The document is at https://github.com/w3c/miniapp-packaging/pull/55/files

**Comment by espinr** [comment]
Closing after merging #55
