### ISSUE TITLE
Redundant definition about allowed filenames?

### ISSUE THREAD

**Issue by pes10k** [w3c/miniapp-packaging#61]
This issue is being filed as part of PING [wide review](https://github.com/w3cping/privacy-request/issues/99).

A fair amount of this spec defines what characters can be used in filenames ([Section 2.1.5.](https://www.w3.org/TR/miniapp-packaging/#file-names)).  This text seems highly redundant with existing text in other W3C notes and documents (for example, https://www.w3.org/TR/international-specs/#file_naming). If possible i suggest your spec not have its own rules for deciding which filenames are legal, and instead refer to other existing documents / specs

This is not a blocking privacy issue, but I'm mentioning it since it came up during the review

**Comment by espinr** [comment]
Totally agreed, @pes10k . Thanks for the heads-up. No reason for duplicating the definition. I'll update the spec pointing to https://www.w3.org/TR/international-specs/#file_naming

**Comment by r12a** [comment]
/TR doc is only a Note and may well be changed at any time. However, the i18n WG has contacted the Unicode Consortium to see whether they'd be interested in maintaining a document similar to the section that you pointed to.  This may provide a more stable reference.
